# the/directory/Gemfile
# frozen_string_literal: true

# Gemfile
source 'https://rubygems.org'

ruby '3.2.2'
# Ruby LSP
gem 'rubocop'
gem 'rubocop-packaging'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'rubocop-shopify'
gem 'rubocop-thread_safety'
gem 'ruby-lsp'
